### ISSUE TITLE
Need help with Koopa parsed result

### ISSUE THREAD

**Issue by shivasharma0691** [krisds/koopa#25]
Hi Kris,

I have started with Koopa parser and i was succesfully able to get XML dump and convert it into XSD schema and generate java classes from it. Now am looking for a way where i can directly read AST into Java objects without converting it into XML or XSD. Is there any way to do that. I did a lot of research but couldn't find a appropriate way. Please suggest if there is any way.

Shiva

**Comment by krisds** [comment]
(as replied on sourceforge)

Hi Shiva,

Yes, of course that's possible. Look at the classes under the “examples" folder to see how you can access the ASTs and start processing them.

Cheers,

Kris
