### ISSUE TITLE
NullPointerException while running JaxenExample 

### ISSUE THREAD

**Issue by hegdemk2004** [krisds/koopa#26]
Hi Kris, I have built the current version of Koopa as-is. When I run JaxenExample class I am getting a NullPointerException on this line of code 

Tree tree = parse.getTarget(KoopaTreeBuilder.class).getTree();

Input is valid.
Exception in thread "main" 
  0 error(s).
  0 warning(s).
java.lang.NullPointerException
	at koopa.examples.jaxen.JaxenSample.main(JaxenSample.java:35)

Has anything changed in the Parse or TreeBuilder? 

Thanks, Mahesh (hegdemk2004@gmail.com)

**Comment by krisds** [comment]
Hey Mahesh,

Yes, that's a small bug. I'll push a fix.

Kris

**Comment by krisds** [comment]
Should be good now.

**Comment by hegdemk2004** [comment]
Works fine now. Thank you for you for the super quick fix! you are the best.

**Comment by krisds** [comment]
Thank you for using Koopa, and helping me make it better. :-)
