### ISSUE TITLE
Parsing Mixed Case COBOL Code? 

### ISSUE THREAD

**Issue by hegdemk2004** [krisds/koopa#28]
I am trying to parse the CPYREPC1.cbl file available at http://www.simotime.com/cpyrep01.htm with the ToXML.java. It fails to parse with message : Error: null Failed to parse. Last successful match: programPrototype < sourceUnit < compilationGroup.

Its one of the simplest programs and I do not see any syntactic issues in the code. Other than probably the code being mixed case or the missing ENVIRONMENT DIVISION - which is really optional. Any clue?

**Comment by krisds** [comment]
It works for me. Here is my input and exported XML: [CPYREPC1.zip](https://github.com/krisds/koopa/files/5825761/CPYREPC1.zip)

(Just FYI: Mixed case does not matter to Koopa when parsing COBOL. Everything is set up to be case insensitive.)
