### ISSUE TITLE
Need a demo of the Koopa COBOL Parser 

### ISSUE THREAD

**Issue by alokebhaduri** [krisds/koopa#29]
Hi Kris

I am a Senior Manager with Hexaware Technologies Ltd.  I am looking for COBOL Parser which can help extract the Program Flow pf COBOL programs.  I found the Koopa Open Source Software as a COBOL Parser from Sourceforge.NET. 

I am looking for a Demo of the Koopa Parser against some sample COBOL programs and would like to understand how does the Koopa COBOL Parser generate the different program flows, procedure division section / paragraph three.  

Also looking for guidelines on how the Koopa COBOL Parser will work.  Please send me a contact and I will send a meeting invite for the Demo and Discussion on the Koopa Tool.

Looking forward to your response.  Please send me your response at **aloke.bhaduri@gmail.com**

**Comment by krisds** [comment]
Have you checked the [guide](https://github.com/krisds/koopa/blob/master/doc/guide/guide.pdf) ? It explains the reasoning behind Koopa in quite some detail.

The best way to explore Koopa's capabilities is to run the app, point it at a source file, and then play with the settings. Everything configurable should be accessible through the menus.
