### ISSUE TITLE
Are there any release notes for the koopa COBOL parser?

### ISSUE THREAD

**Issue by KT1061** [krisds/koopa#31]
I'm currently incorporating the koopa COBOL parser generator into a tool I'm developing.
The version I'm using is koopa-r356.jar which was managed by Sourceforge at the time.
There are many points/features that are not supported in older versions (such as koopa-r356.jar) compared to the latest version.
Since I would like to incorporate the changes that are a part of the latest version, do you have any release notes?

**Comment by krisds** [comment]
Sorry, there are no release notes. Most of the updates since Sourceforge (whose repo I no longer use, but kept for historic reasons) are either bugfixes, or updates to the grammar to be able to process more of the COBOL source.

I try to keep the [README](https://github.com/krisds/koopa/blob/master/README.md) up to date, so that's your best place to find an overview. I also try to make every feature accessible in the UI, so do explore the menu's there to see what's possible.

**Comment by KT1061** [comment]
We are using koopa COBOL parser to analyze legacy systems that are currently in production, and I think it is a very good product.
I would like to continue using the koopa COBOL parser, so would it be possible for you to create and manage tags when there are updates so that I can check for updates?
At present, the koopa Github repo only has the master branch, and it is difficult to know when to incorporate updates, so would it possible for you to make tags so that is easier for the user to check the references regarding important milestones or versions of the codebase, such as a release or a significant change? 

Thanks a lot beforehand.

**Comment by krisds** [comment]
Glad to hear that you are able to make good use of Koopa. It's always motivating to hear such news.

I could, of course, add tags, if that's really useful to you. I haven't seen the point to those yet, as it's mostly just me developing or, lately, just fixing things. There are no big milestones or significant changes planned at the moment.

Additionally, the master branch should always be the stable branch. Anything really new, or breaking, should go into separate branches, until it's ready for release, at which point it will get merged into master. So if you're just tracking whatever is in master you should be good to go.

Having said that, please let me know if you would still benefit from tagged versions, and I'll be happy to give that a try.

**Comment by KT1061** [comment]
Thanks a lot for the response.
I will refer to master branch, so please close the issue.
If there is a need to add tags and manage them in the future, I will let you know. 
It would be really helpful if you could tags during that time.

**Comment by krisds** [comment]
No problem. I will do some work on the support for version numbering in the code, so that when anyone wants tags, I can do some actual clean releases.
