### ISSUE TITLE
IF Grammar

### ISSUE THREAD

**Issue by ccarlenzoli** [krisds/koopa#35]
Sorry if I used this way for submitting the following test case; I'm believing it is an issue so I prefer to contact you in this way. 

I've noticed when parsing cobol a strange behavior in IF Statement management

When comparing this two statements: 

-  EGUCE123-I-NDG = SPACES AND GUCE123-P-BANCA = ZERO OR EGUCE123-I-DATO-COMPL = SPACES 
-  EGUCE123-I-DATO-COMPL = SPACES OR EGUCE123-I-NDG = SPACES AND GUCE123-P-BANCA = ZERO

parsed results (aka the xml output produced from Kappa UI Application) are like this

<img width="1918" alt="image" src="https://github.com/krisds/koopa/assets/1710603/7b4ab540-e7b2-4f1a-aabc-7b8695d2ff8d">

On the left you can see the first case and for what I understood from Grammar can be considered a good result whereas on the right you can see the second case. As you can see Grammar was not able to catch the last part of the Logical Expression (aka AND GUCE123-P-BANCA = ZERO) considering this as "not recognized" cobol code leaving it as "simple" Token sequence.

Is this the expected result?

**Comment by krisds** [comment]
This feels like a bug in the grammar. I'll try take a look this week-end.

**Comment by ccarlenzoli** [comment]
Really Thanks!!!
I'm working on your tool trying to enable a Visitor Pattern for doing some bulk activities trying to Revert code getting at least a Tech Spec readable for Architects... so it is very important to have a full Grammar coverage keeping the current stability of your solution. I want to highlight that I tried several tools but yours it is the only one VERY STABLE!! If code is not caught by specialized Token I can found it in the Tokens.... so the stability is very impressive!!! Hope we will find a global solution... :) Waiting for you!
Best

**Comment by krisds** [comment]
I have tried to reproduce the issue, but I get good results for both variants of condition. Here is a screenshot, showing that it correctly identifies `AND GUCE123-P-BANCA = ZERO` on my end:

<img width="1440" alt="Screenshot 2023-09-30 at 09 03 31" src="https://github.com/krisds/koopa/assets/4458144/2b4b4d32-ca35-46cc-94ef-8db11c6e52c6">

And here is a zip with my test COBOL file, and the corresponding XML output, so you can double check: [issue.zip](https://github.com/krisds/koopa/files/12774152/issue.zip)

I *suspect* you're using an old version of Koopa (my testing was on the latest version from the master branch). Part of why I think that is that the parse on the left side of your screenshot shows that Koopa thinks there is an abbreviated disjunction in your condition, which I'm pretty sure is incorrect, and feels like something I have fixed before.

So: can you please let me know if you're using the latest version of Koopa ? If so, could you provide me with an example source file which gives you an incorrect result ?

PS. Thanks so much for the kind words. It is always great to hear people putting Koopa to good use! And I'm glad it still stands up even against the newer choices available.

**Comment by ccarlenzoli** [comment]
I'll check using your code on my workspace and let you know!

Thanks for helping me!

**Comment by krisds** [comment]
Hey @ccarlenzoli . Any news on whether it worked ?

**Comment by krisds** [comment]
I'm guessing everything is ok. If the problem persists, please open a new ticket.
