### ISSUE TITLE
Bulk Cobol conversion to XML?

### ISSUE THREAD

**Issue by suncorpguy** [krisds/koopa#7]
Hi 

I'm looking for the best way to run a bulk conversion of a number of Cobol programs to XML using Koopa.  

Can I wrap the Koopa functionality into my own Java controller, if so, is there a copy of the class docs anywhere?

Or if someone else has already done something similar, share the code?

Thanks iin advance

**Comment by krisds** [comment]
Hi,

Just run `koopa.app.cli.ToXml` from the command line, and point it at a folder.

You can [find the code here](https://github.com/krisds/koopa/blob/master/src/apps/koopa/app/cli/ToXml.java). If you need to do something custom, that's also a good reference to start from.

**Comment by suncorpguy** [comment]
Thanks Kris, that works well, I guess I was over thinking it.
