### ISSUE TITLE
Problem with AST generation

### ISSUE THREAD

**Issue by Risavk** [krisds/koopa#9]
Hi, 
tried yesterday to test ToXML CLI with testcase cobol programs provided by you (even simplest), and my own... And it does not work. 
It complains about null "targets" list of Flow class. Could you check if everything is working fine on your side ? I can't think about any possible problems on my side ...  
I can't provide you at the moment with any of error messages (computer with source is far, far away)

Problem is raised here : 
`final Tree ast = results.getParse().getTarget(KoopaTreeBuilder.class).getTree();`

**Comment by krisds** [comment]
You're right, there is an NPE at that line. It should be easy to fix.

**Comment by krisds** [comment]
PR #10 should fix it.

**Comment by Risavk** [comment]
Thanks. Will check if only i'll get back :)

**Comment by Risavk** [comment]
Working like a charm :) Thanks. Closing :)
